from widgets.edit import Edit
from widgets.genre import Genre
from widgets.gui import GUI
from widgets.info import Info
from widgets.load import Loading
from widgets.main_table import MainTable
from widgets.musicplayer import MusicPlayer
from widgets.mytreeview import MyTreeView
from widgets.playlist import Playlist
from widgets.search import SearchDialog
from widgets.filter import Filter
from widgets.mylistview import MyListView
from widgets.short_edit import ShortEdit